Tidy up GOV.UK logo hover and focus states
alphagov/govuk-frontend pull request #2171
Opened 2021-03-23 17:25 UTC by 36degrees

Address two minor issues with the hover and focus states for the GOV.UK logo (including product name, when present):

## 1. With product name

When the header includes a product name, the homepage link’s underline (on hover) and the focus state take up an additional 10px on the right hand side, because of the 10px right padding on `govuk-header__product-name`.

| Before | After |
| --- | --- |
| ![Screenshot 2021-03-23 at 17 20 09](https://user-images.githubusercontent.com/121939/112189682-285af080-8bfc-11eb-9a4f-f3d110a6926d.png) | ![Screenshot 2021-03-23 at 17 20 19](https://user-images.githubusercontent.com/121939/112189724-31e45880-8bfc-11eb-848d-2d43bdd612f6.png) |
| ![Screenshot 2021-03-23 at 17 20 13](https://user-images.githubusercontent.com/121939/112189771-40327480-8bfc-11eb-9128-9c30591fb2ae.png) | ![Screenshot 2021-03-23 at 17 20 22](https://user-images.githubusercontent.com/121939/112189772-40cb0b00-8bfc-11eb-8c9f-aa59ff7d277d.png) |

This [padding is there to ensure there is a gap left between the product name and the menu button][1]. Remove it, and add a 10px margin to `govuk-header__link--homepage` instead which achieves the same result but without adding an additional 10px to the hover and focus states.

## 2. Without product name

When the header does not include a product name, the homepage link’s underline (on hover) and the focus state take up an additional 5px on the right hand side, because of a 5px margin on `govuk-header__logotype`.

| Before | After |
| --- | --- |
| ![Screenshot 2021-03-23 at 17 19 17](https://user-images.githubusercontent.com/121939/112189862-59d3bc00-8bfc-11eb-982d-ef567c7f70ca.png) | ![Screenshot 2021-03-23 at 17 19 33](https://user-images.githubusercontent.com/121939/112189861-593b2580-8bfc-11eb-9f91-710ce72154ab.png) |
| ![Screenshot 2021-03-23 at 17 19 42](https://user-images.githubusercontent.com/121939/112189858-58a28f00-8bfc-11eb-9443-5e68446fccd8.png) | ![Screenshot 2021-03-23 at 17 19 37](https://user-images.githubusercontent.com/121939/112189860-593b2580-8bfc-11eb-9bc1-099aabfd87d9.png) |

This margin has been present since the component was added to GOV.UK Frontend, but I believe it’s to ensure there’s a space between GOV.UK and a product name. Remove this margin in favour of a 5px left margin on the product name, so that the margin is only included when there is a product name to show.

[1]: https://github.com/alphagov/govuk-frontend/commit/df413cf6363b537fe37b1b0db5bc40b97424422f

2021-03-24 13:12 UTC, CharlotteDowns approved these changes
I really like this change!

The class `govuk-header__logo` also seems to have some right padding for menu items. Do we know why there was right padding on both the `govuk-header__logo` and `govuk-header__product-name` previously, is it for responsive views or another use case?

2021-03-24 13:29 UTC, christopherthomasdesign approved these changes
Checked out and tested locally, all looks good to me!

2021-03-25 18:06 UTC, hannalaakso requested changes
This is a nicely documented tidy-up @36degrees 👍 

However, it seems that there's now some extra margin to the left of the product name when it's on a new line. The GOV.UK text also seems to have slightly moved. [Preview](https://govuk-frontend-pr-2171.herokuapp.com/components/header/with-product-name/preview).

2021-03-30 08:50 UTC, 36degrees commented
@hannalaakso I've changed the approach for the second fix, by removing the margin if the `__logotype` element is the last child – in which case, there is no product name and so there's no need for the margin.

I think that addresses the issue you raised?

2021-04-06 10:19 UTC, hannalaakso approved these changes
@36degrees Looks great 🎉  I opened https://github.com/alphagov/govuk-frontend/issues/2181 for the other issues I spotted to do with the product name hover/focus states (nothing to do with the changes in this PR).

2021-04-06 10:56 UTC, merged