Port exit this page from 4.7
alphagov/govuk-frontend pull request #3953
Opened 2023-07-11 17:28 UTC by owenatgov

Ports the [exit this page component](https://design-system.service.gov.uk/components/exit-this-page/) from the 4.7.0 release to `main`, including refactoring the js to ES2015 in line with https://github.com/alphagov/govuk-frontend/pull/3771

Includes changes from the following PRs:
- https://github.com/alphagov/govuk-frontend/pull/2545
- https://github.com/alphagov/govuk-frontend/pull/3874
- https://github.com/alphagov/govuk-frontend/pull/3878

Additionally supersedes https://github.com/alphagov/govuk-frontend/pull/3880

Fixes https://github.com/alphagov/govuk-frontend/issues/3840

2023-07-12 09:11 UTC, colinrotherham requested changes
Nicely done @owenatgov

Few minor snags but nothing big at all. I think we'd best split out non-port changes (like renaming selector properties) unless it was for consistency with v5

2023-07-12 09:11 UTC, colinrotherham commented on packages/govuk-frontend/src/govuk/components/exit-this-page/exit-this-page.mjs
> +  init () {
Thanks for moving this higher up 😊

2023-07-12 09:11 UTC, colinrotherham commented on packages/govuk-frontend/src/govuk/components/exit-this-page/accessibility.test.mjs
> +    it('passes accessibility tests', async () => {
Fab work. Cheers for moving the accessibility tests into the new format 🙌

2023-07-14 15:07 UTC, colinrotherham commented on packages/govuk-frontend/src/govuk/components/exit-this-page/exit-this-page.test.js
> +      const href = await page.$eval(buttonClass, el => el.getAttribute('href'))
Sorry @owenatgov if we're keeping `buttonClass` can we update the `it()` description?

>navigates to the href of the ~skiplink~ button

2023-07-14 15:08 UTC, colinrotherham commented on packages/govuk-frontend/src/govuk/components/exit-this-page/exit-this-page.test.js
> +      const href = await page.$eval(buttonClass, el => el.getAttribute('href'))
There's one on line 66 to check too

2023-07-14 15:11 UTC, owenatgov commented on packages/govuk-frontend/src/govuk/components/exit-this-page/exit-this-page.test.js
> +      const href = await page.$eval(buttonClass, el => el.getAttribute('href'))
Ah sorry I misread your comment! Will update now.

2023-07-14 15:29 UTC, colinrotherham approved these changes
🚀

2023-07-14 15:32 UTC, merged